# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c397e4f131193bd08e4b28261696975783744e68608cf5262df4fcb4a2d56c9de5d35ffa061d269732d6f3bec4b9509befb9b6689dd395b591fa26a517fa79e8

test:
  secret_key_base: 2d8f2cd80094208f5afc98ac8169940721551e705b94c6c527fcff5e5bf48594688bf722df872a1230da3befee5de72a55ff7c237f883050c1fbd9a5e5071056

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
